import pygame as pg
import moderngl as mgl


class Texture:
    def __init__(self, app):
        self.app = app
        self.ctx = app.ctx
        self.textures = {}
        self.textures[0] = self.get_texture(path='textures/transparent.png')
        self.textures[1] = self.get_texture(path='textures/img_1.png')
        self.textures[2] = self.get_texture(path='textures/img_2.png')
        self.textures['cat'] = self.get_texture(path='objects/cat/20430_cat_diff_v1.jpg')
        self.textures['city1'] = self.get_texture(path='objects/city1/textures/lambert1.002_baseColor.png')
        self.textures['city2'] = self.get_texture(path='objects/city2/textures/VC_Map_Upscaled_baseColor.png')
        self.textures['city3'] = self.get_texture(path='objects/city3/textures/GTA1 San Andreas-art-scale-2_00x.png')
        self.textures['car1'] = self.get_texture(path='objects/car/textures/nissan_370_red1.png')
        self.textures['car2'] = self.get_texture(path='objects/car/textures/nissan_370_red2.png')
        self.textures['car3'] = self.get_texture(path='objects/car/textures/nissan_370_red3.png')
        self.textures['car4'] = self.get_texture(path='objects/car/textures/nissan_370_red4.png')
        self.textures['car5'] = self.get_texture(path='objects/car/textures/nissan_370_red5.png')
        self.textures['car6'] = self.get_texture(path='objects/car/textures/nissan_370_red6.png')
        
        self.textures['city4_1'] = self.get_texture(path='objects/city4/textures/city_base.png')
        self.textures['city4_2'] = self.get_texture(path='objects/city4/textures/city_hospital.png')
        self.textures['city4_3'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_4'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_5'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_6'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_7'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_8'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_9'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_10'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_11'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_12'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_13'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_14'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_15'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_16'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_17'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_18'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_19'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_20'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_21'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_22'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_23'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_24'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_25'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_26'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_27'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_28'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_29'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_30'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_31'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_32'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_33'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_34'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_35'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_36'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_37'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_38'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_39'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_40'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_41'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_42'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_43'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_44'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_45'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_46'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_47'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_48'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_49'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_50'] = self.get_texture(path='objects/city4/textures/city_factory.png')
        self.textures['city4_51'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_52'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_53'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_54'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_55'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_56'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_57'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_58'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_59'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_60'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_61'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_62'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_63'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_84'] = self.get_texture(path='objects/city4/textures/city_cancha.png')
        self.textures['city4_85'] = self.get_texture(path='objects/city4/textures/city_lavanderia.png')
        self.textures['city4_86'] = self.get_texture(path='objects/city4/textures/city_lavanderia.png')
        self.textures['city4_87'] = self.get_texture(path='objects/city4/textures/city_lavanderia.png')
        self.textures['city4_88'] = self.get_texture(path='objects/city4/textures/city_lavanderia.png')
        self.textures['city4_89'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_90'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_91'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_92'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_93'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_94'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_95'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_96'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_97'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_98'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_99'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_100'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_101'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_102'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_103'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_104'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_105'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_106'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_107'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_108'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_109'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_110'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_111'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_112'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_113'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_114'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_115'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_116'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_117'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_118'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_119'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_120'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_121'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_122'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_123'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_124'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_125'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_126'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_127'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_128'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_129'] = self.get_texture(path='objects/city4/textures/city_paramount.png')
        self.textures['city4_130'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_131'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_132'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_133'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_134'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_135'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_136'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_137'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_138'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_139'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_140'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_141'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_142'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_143'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_144'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_145'] = self.get_texture(path='objects/city4/textures/city_pawn.png')
        self.textures['city4_146'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_147'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_148'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_149'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_150'] = self.get_texture(path='objects/city4/textures/city_cancha_edificio.png')
        self.textures['city4_151'] = self.get_texture(path='objects/city4/textures/city_base.png')
        self.textures['city4_152'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_153'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_154'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_155'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_156'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_157'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_158'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_159'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_160'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_161'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_162'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_163'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_164'] = self.get_texture(path='objects/city4/textures/city_clausurado.png')
        self.textures['city4_165'] = self.get_texture(path='objects/city4/textures/city_lamppost.png')
        self.textures['city4_166'] = self.get_texture(path='objects/city4/textures/city_lamppost.png')
        self.textures['city4_167'] = self.get_texture(path='objects/city4/textures/city_lamppost.png')
        self.textures['city4_168'] = self.get_texture(path='objects/city4/textures/city_lamppost.png')
        
        self.textures['skybox'] = self.get_texture_cube(dir_path='textures/skybox1/', ext='png')
        self.textures['depth_texture'] = self.get_depth_texture()



    def get_depth_texture(self):
        depth_texture = self.ctx.depth_texture(self.app.WIN_SIZE)
        depth_texture.repeat_x = False
        depth_texture.repeat_y = False
        return depth_texture


    def get_texture_cube(self, dir_path, ext='png'):
        faces = ['right', 'left', 'top', 'bottom'] + ['front', 'back'][::-1]
        # textures = [pg.image.load(dir_path + f'{face}.{ext}').convert() for face in faces]
        textures = []
        for face in faces:
            texture = pg.image.load(dir_path + f'{face}.{ext}').convert()
            if face in ['right', 'left', 'front', 'back']:
                texture = pg.transform.flip(texture, flip_x=True, flip_y=False)
            else:
                texture = pg.transform.flip(texture, flip_x=False, flip_y=True)
            textures.append(texture)

        size = textures[0].get_size()
        texture_cube = self.ctx.texture_cube(size=size, components=3, data=None)

        for i in range(6):
            texture_data = pg.image.tostring(textures[i], 'RGB')
            texture_cube.write(face=i, data=texture_data)

        return texture_cube

    def get_texture(self, path):
        texture = pg.image.load(path).convert()
        texture = pg.transform.flip(texture, flip_x=False, flip_y=True)
        texture = self.ctx.texture(size=texture.get_size(), components=3,
                                   data=pg.image.tostring(texture, 'RGB'))
        # mipmaps
        texture.filter = (mgl.LINEAR_MIPMAP_LINEAR, mgl.LINEAR)
        texture.build_mipmaps()
        # AF
        texture.anisotropy = 32.0
        return texture

    def destroy(self):
        [tex.release() for tex in self.textures.values()]